import * as React from 'npm:react@18.3.1'
import {
  Body, Container, Head, Heading, Html, Preview, Text, Section, Hr, Button,
} from 'npm:@react-email/components@0.0.22'
import type { TemplateEntry } from './registry.ts'

const SITE_NAME = "HFAI"

interface WeeklyReportProps {
  orgName?: string
  totalSystems?: number
  highRiskSystems?: number
  totalViolations?: number
  openViolations?: number
  resolvedViolations?: number
  totalReviews?: number
  activeRules?: number
  reportDate?: string
  dashboardUrl?: string
}

const WeeklyComplianceReportEmail = ({
  orgName = 'Your Organization',
  totalSystems = 0,
  highRiskSystems = 0,
  totalViolations = 0,
  openViolations = 0,
  resolvedViolations = 0,
  totalReviews = 0,
  activeRules = 0,
  reportDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
  dashboardUrl = 'https://www.hfa-i.org/customer/compliance',
}: WeeklyReportProps) => (
  <Html lang="en" dir="ltr">
    <Head />
    <Preview>Weekly EU AI Act Compliance Report — {orgName}</Preview>
    <Body style={main}>
      <Container style={container}>
        <Text style={eyebrow}>WEEKLY COMPLIANCE REPORT</Text>
        <Heading style={h1}>
          AI Governance Summary
        </Heading>
        <Text style={subtitle}>
          {orgName} — {reportDate}
        </Text>

        <Hr style={divider} />

        <Section style={statsGrid}>
          <table width="100%" cellPadding="0" cellSpacing="0" style={{ borderCollapse: 'collapse' as const }}>
            <tr>
              <td style={statCell}>
                <Text style={statValue}>{totalSystems}</Text>
                <Text style={statLabel}>AI Systems</Text>
              </td>
              <td style={statCell}>
                <Text style={statValueAmber}>{highRiskSystems}</Text>
                <Text style={statLabel}>High-Risk</Text>
              </td>
              <td style={statCell}>
                <Text style={statValue}>{activeRules}</Text>
                <Text style={statLabel}>Active Rules</Text>
              </td>
            </tr>
          </table>
        </Section>

        <Section style={sectionBox}>
          <Text style={sectionTitle}>Violation Overview</Text>
          <table width="100%" cellPadding="0" cellSpacing="0" style={{ borderCollapse: 'collapse' as const }}>
            <tr>
              <td style={metricRow}><Text style={metricLabel}>Total Violations</Text></td>
              <td style={metricRowRight}><Text style={metricValue}>{totalViolations}</Text></td>
            </tr>
            <tr>
              <td style={metricRow}><Text style={metricLabelRed}>Open / Unresolved</Text></td>
              <td style={metricRowRight}><Text style={metricValueRed}>{openViolations}</Text></td>
            </tr>
            <tr>
              <td style={metricRow}><Text style={metricLabelGreen}>Resolved</Text></td>
              <td style={metricRowRight}><Text style={metricValueGreen}>{resolvedViolations}</Text></td>
            </tr>
          </table>
        </Section>

        <Section style={sectionBox}>
          <Text style={sectionTitle}>Human Oversight</Text>
          <Text style={text}>
            <strong>{totalReviews}</strong> human review decisions have been recorded across your organization.
          </Text>
        </Section>

        <Section style={{ textAlign: 'center' as const, margin: '32px 0' }}>
          <Button style={ctaButton} href={dashboardUrl}>
            View Full Compliance Dashboard
          </Button>
        </Section>

        <Hr style={divider} />

        <Text style={footer}>
          This is an automated weekly report generated by {SITE_NAME}.<br />
          EU AI Act (Regulation 2024/1689) compliance monitoring is active.
        </Text>
      </Container>
    </Body>
  </Html>
)

export const template = {
  component: WeeklyComplianceReportEmail,
  subject: (data: Record<string, any>) => `Weekly Compliance Report — ${data?.orgName || 'HFAI'}`,
  displayName: 'Weekly compliance report',
  previewData: {
    orgName: 'Acme Corp',
    totalSystems: 5,
    highRiskSystems: 2,
    totalViolations: 18,
    openViolations: 3,
    resolvedViolations: 15,
    totalReviews: 12,
    activeRules: 8,
    reportDate: 'March 24, 2026',
    dashboardUrl: 'https://www.hfa-i.org/customer/compliance',
  },
} satisfies TemplateEntry

const main = { backgroundColor: '#ffffff', fontFamily: "'Inter', Arial, sans-serif" }
const container = { padding: '32px 28px', maxWidth: '560px', margin: '0 auto' }
const eyebrow = { fontSize: '11px', fontWeight: '700' as const, color: '#d97706', letterSpacing: '1.5px', margin: '0 0 8px', textTransform: 'uppercase' as const }
const h1 = { fontSize: '24px', fontWeight: '700' as const, color: '#1a1a1a', margin: '0 0 8px' }
const subtitle = { fontSize: '14px', color: '#6b7280', margin: '0 0 24px' }
const divider = { borderColor: '#e5e7eb', margin: '24px 0' }
const text = { fontSize: '14px', color: '#55575d', lineHeight: '1.6', margin: '0 0 16px' }

const statsGrid = { margin: '0 0 24px' }
const statCell = { textAlign: 'center' as const, padding: '16px 8px', width: '33.33%' }
const statValue = { fontSize: '28px', fontWeight: '700' as const, color: '#1a1a1a', margin: '0 0 4px' }
const statValueAmber = { fontSize: '28px', fontWeight: '700' as const, color: '#d97706', margin: '0 0 4px' }
const statLabel = { fontSize: '11px', color: '#9ca3af', margin: '0', textTransform: 'uppercase' as const, letterSpacing: '0.5px' }

const sectionBox = { backgroundColor: '#f9fafb', borderRadius: '8px', padding: '20px', margin: '0 0 16px' }
const sectionTitle = { fontSize: '14px', fontWeight: '700' as const, color: '#1a1a1a', margin: '0 0 12px' }

const metricRow = { padding: '6px 0' }
const metricRowRight = { padding: '6px 0', textAlign: 'right' as const }
const metricLabel = { fontSize: '14px', color: '#55575d', margin: '0' }
const metricLabelRed = { fontSize: '14px', color: '#dc2626', margin: '0' }
const metricLabelGreen = { fontSize: '14px', color: '#16a34a', margin: '0' }
const metricValue = { fontSize: '14px', fontWeight: '600' as const, color: '#1a1a1a', margin: '0' }
const metricValueRed = { fontSize: '14px', fontWeight: '600' as const, color: '#dc2626', margin: '0' }
const metricValueGreen = { fontSize: '14px', fontWeight: '600' as const, color: '#16a34a', margin: '0' }

const ctaButton = {
  backgroundColor: '#d97706',
  color: '#ffffff',
  fontSize: '14px',
  fontWeight: '600' as const,
  padding: '12px 28px',
  borderRadius: '6px',
  textDecoration: 'none',
}

const footer = { fontSize: '12px', color: '#9ca3af', margin: '0', lineHeight: '1.5' }
