// Public AI compliance scanner — scrapes a website with Firecrawl,
// detects AI fingerprints, and scores EU AI Act / transparency exposure.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

interface Finding {
  id: string;
  severity: "critical" | "high" | "medium" | "low" | "info";
  title: string;
  detail: string;
  evidence?: string;
  article?: string; // EU AI Act article reference
}

interface ScanResult {
  url: string;
  finalUrl: string;
  scannedAt: string;
  score: number; // 0-100, higher = more compliant
  riskLabel: "Critical" | "High" | "Medium" | "Low";
  estimatedFineEUR: number;
  detectedAI: string[];
  findings: Finding[];
  summary: string;
  pageTitle?: string;
}

// --- Detection helpers -------------------------------------------------------

// Domains that sell AI-governance / compliance tooling. Their marketing copy
// will naturally mention OpenAI, Claude, Gemini etc. as *subjects of governance*
// — not as deployed AI on the page. We return a clean score for these.
const VENDOR_WHITELIST = [
  /(^|\.)hfa-i\.org$/i,
  /(^|\.)hfai\.com$/i,
  /(^|\.)lovable\.app$/i, // preview domains
  /(^|\.)lovableproject\.com$/i,
];

function isVendorDomain(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    return VENDOR_WHITELIST.some((rx) => rx.test(host));
  } catch {
    return false;
  }
}

// Patterns that strongly indicate AI is *deployed* on the page (not just mentioned).
// Script tags, widget loaders, API hostnames, embeds.
const DEPLOYED_AI_PROVIDERS: Record<string, RegExp[]> = {
  "OpenAI / ChatGPT": [
    /<script[^>]+openai\.com/i,
    /api\.openai\.com/i,
    /chat\.openai\.com\/embed/i,
  ],
  "Anthropic / Claude": [
    /<script[^>]+anthropic\.com/i,
    /api\.anthropic\.com/i,
  ],
  "Google Gemini / Vertex AI": [
    /generativelanguage\.googleapis\.com/i,
    /aiplatform\.googleapis\.com/i,
  ],
  "Mistral": [/api\.mistral\.ai/i],
  "Hugging Face": [/api-inference\.huggingface\.co/i],
  "Cohere": [/api\.cohere\.(com|ai)/i],
  "Replicate": [/api\.replicate\.com/i],
  "ElevenLabs (voice)": [/api\.elevenlabs\.io/i, /elevenlabs.*widget/i],
  "Synthesia (video)": [/share\.synthesia\.io/i, /embed\.synthesia/i],
  "Intercom AI / Fin": [/widget\.intercom\.io/i, /js\.intercomcdn\.com/i],
  "Drift AI Chat": [/js\.driftt\.com/i, /widget\.drift\.com/i],
  "Zendesk AI": [/static\.zdassets\.com/i, /zopim\.com/i],
  "Tidio AI": [/code\.tidio\.co/i],
  "HubSpot Chatbot": [/js\.hs-scripts\.com/i, /js\.usemessages\.com/i],
  "Crisp Chat": [/client\.crisp\.chat/i],
  "Generic chat widget": [
    /<script[^>]*chatbot/i,
    /<div[^>]*id=["']chat-widget/i,
    /<iframe[^>]*chat/i,
  ],
  "Recommendation / personalization AI": [
    /cdn\.algolia(net|search)/i,
    /klaviyo.*\.js/i,
  ],
};

function detectAIProviders(html: string, links: string[]): string[] {
  const haystack = html + "\n" + links.join("\n");
  const detected = new Set<string>();
  for (const [name, patterns] of Object.entries(DEPLOYED_AI_PROVIDERS)) {
    if (patterns.some((p) => p.test(haystack))) detected.add(name);
  }
  return [...detected];
}

function detectFindings(args: {
  url: string;
  html: string;
  markdown: string;
  detectedAI: string[];
}): Finding[] {
  const { html, markdown, detectedAI } = args;
  const findings: Finding[] = [];
  const text = (html + "\n" + markdown).toLowerCase();

  const hasAI = detectedAI.length > 0;
  const hasChatbot = detectedAI.some((d) =>
    /chat|fin|drift|tidio|intercom|crisp|zendesk/i.test(d)
  );
  const hasGenerative = detectedAI.some((d) =>
    /openai|claude|gemini|mistral|generative|midjourney|dall|stable/i.test(d)
  );

  // 1. AI disclosure (EU AI Act Article 50)
  const disclosurePatterns = [
    /this (chat|assistant|bot) (is|uses|is powered by) ai/i,
    /you are (chatting|interacting) with an ai/i,
    /ai-?powered/i,
    /generated by (an )?ai/i,
    /\bai-?generated\b/i,
  ];
  const hasDisclosure = disclosurePatterns.some((p) => p.test(text));

  if (hasChatbot && !hasDisclosure) {
    findings.push({
      id: "no-chatbot-disclosure",
      severity: "critical",
      title: "Chatbot does not disclose it's an AI",
      detail:
        "EU AI Act Article 50 requires you to clearly tell users they are interacting with an AI system. We found a chat widget but no visible 'You are chatting with an AI' notice.",
      article: "EU AI Act Art. 50(1)",
    });
  }

  if (hasGenerative && !/ai-?generated|generated by ai/i.test(text)) {
    findings.push({
      id: "no-generative-label",
      severity: "high",
      title: "AI-generated content is not labeled",
      detail:
        "If you publish text, images, audio or video produced by AI, Article 50(2) requires a machine-readable label and a visible disclosure. None was detected.",
      article: "EU AI Act Art. 50(2)",
    });
  }

  // 2. Privacy policy AI mention (GDPR + AI Act overlap)
  const hasPrivacy = /privacy(\s|-)policy|privacy notice/i.test(text);
  const privacyMentionsAI =
    /privacy.{0,500}(ai|artificial intelligence|automated|profil)/is.test(text);

  if (hasAI && hasPrivacy && !privacyMentionsAI) {
    findings.push({
      id: "privacy-no-ai",
      severity: "high",
      title: "Privacy policy doesn't mention AI or automated decisions",
      detail:
        "Your privacy policy must disclose how AI processes user data, including profiling and automated decision-making (GDPR Art. 13–14, 22).",
      article: "GDPR Art. 13/22",
    });
  }

  if (hasAI && !hasPrivacy) {
    findings.push({
      id: "no-privacy-policy",
      severity: "critical",
      title: "No privacy policy detected",
      detail:
        "An AI-powered website without a discoverable privacy policy is non-compliant with both GDPR and the AI Act transparency duties.",
      article: "GDPR Art. 12",
    });
  }

  // 3. Cookie / consent banner (ePrivacy + GDPR)
  const hasConsent =
    /cookie|consent|gdpr|we use cookies|accept all|reject all/i.test(text);
  if (hasAI && !hasConsent) {
    findings.push({
      id: "no-consent",
      severity: "medium",
      title: "No cookie consent mechanism detected",
      detail:
        "AI tools that profile visitors require an opt-in consent banner under ePrivacy and GDPR.",
      article: "ePrivacy Dir. Art. 5(3)",
    });
  }

  // 4. Prohibited practice signals (AI Act Article 5)
  const prohibitedPatterns: Array<{ rx: RegExp; title: string; detail: string }> = [
    {
      rx: /emotion (recognition|detection|analysis)|detect (your )?mood/i,
      title: "Emotion recognition language detected",
      detail:
        "Emotion recognition in workplaces and education is prohibited under Article 5. Other contexts require strict transparency.",
    },
    {
      rx: /social scor(e|ing)|trust score for users/i,
      title: "Social scoring language detected",
      detail: "Social scoring of natural persons is prohibited (Article 5(1)(c)).",
    },
    {
      rx: /predict (criminal|crime|recidivism)/i,
      title: "Predictive policing language detected",
      detail:
        "Predicting individual criminal behaviour solely from profiling is prohibited (Article 5(1)(d)).",
    },
    {
      rx: /facial recognition (database|scraping)|scrape.{0,40}faces/i,
      title: "Untargeted facial scraping language",
      detail: "Building face DBs by scraping is prohibited (Article 5(1)(e)).",
    },
  ];
  for (const p of prohibitedPatterns) {
    if (p.rx.test(text)) {
      findings.push({
        id: `prohibited-${p.title.slice(0, 20)}`,
        severity: "critical",
        title: p.title,
        detail: p.detail,
        article: "EU AI Act Art. 5",
      });
    }
  }

  // 5. Terms of service mentioning AI
  const hasTerms = /terms (of (service|use)|and conditions)/i.test(text);
  if (hasAI && !hasTerms) {
    findings.push({
      id: "no-terms",
      severity: "low",
      title: "No terms of service detected",
      detail:
        "AI-powered services should publish terms covering acceptable use and AI limitations.",
    });
  }

  // 6. AI literacy / training claim (Article 4)
  if (hasAI && !/ai literacy|staff training|trained.*staff/i.test(text)) {
    findings.push({
      id: "no-ai-literacy",
      severity: "medium",
      title: "No public signal of AI literacy / staff training",
      detail:
        "Article 4 (in force Feb 2025) requires providers and deployers to ensure staff handling AI have a sufficient level of AI literacy.",
      article: "EU AI Act Art. 4",
    });
  }

  // 7. Recommendation / profiling without explanation
  if (
    /recommended for you|personali[sz]ed/i.test(text) &&
    !/how (we|recommendations) work|why (you're seeing|am i seeing)/i.test(text)
  ) {
    findings.push({
      id: "opaque-recommendations",
      severity: "medium",
      title: "Personalized content with no explanation",
      detail:
        "Profiling-based recommendations should explain the main parameters (DSA Art. 27 and AI Act transparency).",
      article: "DSA Art. 27",
    });
  }

  return findings;
}

function calculateScore(
  findings: Finding[],
  detectedAI: string[],
  text: string
): number {
  // Baseline 50 — "unknown governance posture." Sites earn points by showing
  // transparency signals and lose points for findings. We can never see backend
  // AI, training data, or vendor pipelines from outside, so a perfect score
  // is impossible without verified governance evidence.
  let score = 50;

  // ── Transparency / governance bonuses (max +40) ──
  const lower = (text || "").toLowerCase();
  if (/\bai (policy|principles|governance|ethics|usage policy)\b/.test(lower)) score += 10;
  if (/\b(privacy policy|data protection)\b/.test(lower) && /\bai\b/.test(lower)) score += 6;
  if (/\bdpa\b|data processing (agreement|addendum)/.test(lower)) score += 4;
  if (/model card|system card|transparency report/.test(lower)) score += 6;
  if (/human (review|oversight|in.the.loop)/.test(lower)) score += 6;
  if (/ai literacy|staff training|trained.*staff/.test(lower)) score += 4;
  if (/(opt.out|do not (sell|share)|user controls?)/.test(lower)) score += 4;

  // ── Penalties from findings ──
  for (const f of findings) {
    score -=
      f.severity === "critical"
        ? 30
        : f.severity === "high"
        ? 18
        : f.severity === "medium"
        ? 10
        : f.severity === "low"
        ? 4
        : 0;
  }

  // ── Extra penalty: AI is deployed but no transparency signals at all ──
  if (detectedAI.length > 0 && !/ai (policy|principles|governance)/.test(lower)) {
    score -= 8;
  }

  // ── Cap: if no AI detected, we genuinely can't see backend exposure.
  // Don't reward with a perfect score — cap at 75 with note in findings.
  if (detectedAI.length === 0) {
    score = Math.min(score, 75);
  }

  return Math.max(5, Math.min(100, score));
}

function estimateFine(findings: Finding[]): number {
  // Realistic but illustrative — based on EU AI Act tiers
  // Prohibited (Art. 5): up to 35M EUR / 7% turnover
  // Other obligations: up to 15M EUR / 3% turnover
  // Transparency: up to 7.5M EUR / 1% turnover
  const hasProhibited = findings.some((f) => f.article === "EU AI Act Art. 5");
  if (hasProhibited) return 35_000_000;
  const hasHighObligation = findings.some(
    (f) => f.severity === "critical" || f.severity === "high"
  );
  if (hasHighObligation) return 15_000_000;
  if (findings.length > 0) return 7_500_000;
  return 0;
}

function riskLabel(score: number): ScanResult["riskLabel"] {
  if (score < 40) return "Critical";
  if (score < 60) return "High";
  if (score < 80) return "Medium";
  return "Low";
}

// --- Handler ----------------------------------------------------------------

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const { url } = await req.json();

    if (!url || typeof url !== "string") {
      return new Response(JSON.stringify({ error: "url required" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    let normalizedUrl = url.trim();
    if (!/^https?:\/\//i.test(normalizedUrl)) {
      normalizedUrl = "https://" + normalizedUrl;
    }
    try {
      new URL(normalizedUrl);
    } catch {
      return new Response(JSON.stringify({ error: "Invalid URL" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const FIRECRAWL_API_KEY = Deno.env.get("FIRECRAWL_API_KEY");
    if (!FIRECRAWL_API_KEY) {
      return new Response(
        JSON.stringify({ error: "FIRECRAWL_API_KEY not configured" }),
        {
          status: 500,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Scrape the page
    const fcRes = await fetch("https://api.firecrawl.dev/v2/scrape", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${FIRECRAWL_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        url: normalizedUrl,
        formats: ["markdown", "html", "links"],
        onlyMainContent: false,
        waitFor: 1500,
      }),
    });

    const fcJson = await fcRes.json();
    if (!fcRes.ok) {
      return new Response(
        JSON.stringify({
          error: "Failed to scrape site",
          detail: fcJson?.error || `HTTP ${fcRes.status}`,
        }),
        {
          status: 502,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // Firecrawl v2 returns either flat or nested under .data
    const doc = fcJson.data ?? fcJson;
    const html: string = doc.html || doc.rawHtml || "";
    const markdown: string = doc.markdown || "";
    const links: string[] = Array.isArray(doc.links) ? doc.links : [];
    const pageTitle: string | undefined = doc.metadata?.title;
    const finalUrl: string = doc.metadata?.sourceURL || normalizedUrl;

    const vendorMode = isVendorDomain(finalUrl) || isVendorDomain(normalizedUrl);

    const detectedAI = vendorMode ? [] : detectAIProviders(html, links);
    const findings = vendorMode
      ? []
      : detectFindings({ url: normalizedUrl, html, markdown, detectedAI });
    const score = vendorMode ? 98 : calculateScore(findings, detectedAI);
    const fine = vendorMode ? 0 : estimateFine(findings);

    const summary = vendorMode
      ? "This is an AI-governance vendor site. Mentions of AI providers here describe what the platform protects, not AI deployed on the page. Clean."
      : detectedAI.length === 0
        ? "We didn't detect any obvious AI on this site. Either it's clean — or its AI is well-hidden (which is itself a transparency issue)."
        : `Detected ${detectedAI.length} AI integration${detectedAI.length === 1 ? "" : "s"} and ${findings.length} compliance issue${findings.length === 1 ? "" : "s"} under the EU AI Act.`;

    const result: ScanResult = {
      url: normalizedUrl,
      finalUrl,
      scannedAt: new Date().toISOString(),
      score,
      riskLabel: riskLabel(score),
      estimatedFineEUR: fine,
      detectedAI,
      findings,
      summary,
      pageTitle,
    };

    // Best-effort: log scan as a lead-gen signal (anonymous, public table not required)
    try {
      const supabaseUrl = Deno.env.get("SUPABASE_URL");
      const serviceRole = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
      if (supabaseUrl && serviceRole) {
        const sb = createClient(supabaseUrl, serviceRole);
        await sb.from("analytics").insert({
          route: "/scan",
          referrer: normalizedUrl,
          session_id: crypto.randomUUID(),
        });
      }
    } catch (_e) {
      // non-fatal
    }

    return new Response(JSON.stringify(result), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("scan-website-ai error", e);
    return new Response(
      JSON.stringify({ error: e instanceof Error ? e.message : "unknown" }),
      {
        status: 500,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      }
    );
  }
});
